import React from "react";

const TermsOfUse = () => {
  return (
    <div className="bg-[#f6f1e8] text-black min-h-[60vh]">
      <section className="max-w-4xl mx-auto py-14 sm:py-16 px-4 sm:px-6 lg:px-8 space-y-6">
        <p className="uppercase tracking-[0.18em] text-[10px] sm:text-[11px] font-semibold text-[#ff4b00]">
          TERMS OF USE
        </p>
        <h1 className="text-[clamp(2rem,3vw,2.6rem)] font-black leading-tight">
          Please read this before using FluentFox.
        </h1>
        <p className="text-sm md:text-[15px] text-[#3b2b1b] leading-relaxed">
          FluentFox is in private beta. By requesting access or using the app,
          you agree to these high‑level terms. A more detailed legal version may
          replace this page later.
        </p>

        <div className="space-y-4 text-[13px] mt-2">
          <div>
            <h2 className="font-semibold mb-1 text-[14px]">
              1. Practice‑only tool (no live interview use)
            </h2>
            <p className="text-[12px] text-[#4b3520]">
              FluentFox is intended only for personal practice and preparation.
              It is not designed or recommended to be used{" "}
              <strong>during live interviews, assessments, or exams</strong>,
              whether online or in‑person. You are solely responsible for how you
              use the product.
            </p>
          </div>

          <div>
            <h2 className="font-semibold mb-1 text-[14px]">
              2. No guarantees of outcomes
            </h2>
            <p className="text-[12px] text-[#4b3520]">
              FluentFox does not guarantee interview invitations, job offers,
              promotions, or any other outcome. It is a practice assistant, not a
              replacement for your own preparation, judgment, or performance.
            </p>
          </div>

          <div>
            <h2 className="font-semibold mb-1 text-[14px]">
              3. Not professional advice
            </h2>
            <p className="text-[12px] text-[#4b3520]">
              Content generated by FluentFox (including suggested answers and
              guidance) is provided “as is” for educational and practice purposes
              only. It is not legal, career, or professional advice.
            </p>
          </div>

          <div>
            <h2 className="font-semibold mb-1 text-[14px]">4. Fair use</h2>
            <p className="text-[12px] text-[#4b3520]">
              You agree not to misuse FluentFox, including (but not limited to)
              trying to reverse engineer the system, attack the service, or use
              it in ways that violate applicable laws, exam rules, or company
              policies.
            </p>
          </div>

          <div>
            <h2 className="font-semibold mb-1 text-[14px]">
              5. Changes to the product
            </h2>
            <p className="text-[12px] text-[#4b3520]">
              Features, pricing, and availability may change over time. We may
              modify, suspend, or discontinue parts of FluentFox as we improve
              the product.
            </p>
          </div>

          <p className="text-[11px] text-[#7a5a3a]">
            By requesting access or using FluentFox, you confirm that you
            understand it is a practice‑only tool and that you remain responsible
            for your own choices and behavior in any real‑world interview or
            assessment.
          </p>
        </div>
      </section>
    </div>
  );
};

export default TermsOfUse;